---
- name: Deploy Flask App
  hosts: all
  become: yes

  tasks:
    - name: Add the default centos repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        state: present

    - name: Install packages
      package:
        name:
          - python3
          - python3-pip
          - git

    - name: Create the destination folder
      file:
        path: /opt/flaskwebapp
        state: directory

    - name: Clone the repository
      git:
        repo: https://github.com/elvisomofezi/Flask.git
        dest: /opt/flaskwebapp

    - name: Install Flask and its dependencies
      pip:
        name: flask
        virtualenv: /opt/flask-env
        chdir: /opt/flaskwebapp

    - name: Start the Flask App
      command: /opt/flask-env/bin/python3 /opt/flaskwebapp/flasktest.py
      async: 1
      poll: 0
